Repository doctrine/instantiator, pull requests merged in 2023-12, with the labels that each got.

#103 PHP 8.3 support tests
  .github/workflows/continuous-integration.yml
  .github/workflows/phpbench.yml
Labels: CI

#105 Bump CI workflows
  .github/workflows/coding-standards.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/phpbench.yml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#107 Doctrine CS 12
  composer.json
Labels: Static Analysis

#106 Make data providers static
  composer.json
  tests/DoctrineTest/InstantiatorTest/InstantiatorTest.php
Labels: Test Suite
